# Generated by Django 5.1.2 on 2024-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='gemini_output',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
